routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CertificateController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\LanguageSwitcherController;
use App\Http\Controllers\LicenseController;
use App\Http\Controllers\PartnerController;
use App\Http\Controllers\QuestionnaireController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\TrainingController;
use App\Http\Controllers\UniversityController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WorkController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware(['language'])->group(function () {
    Route::get('/', [CompanyController::class, 'index']);
    Route::resource('categories', CategoryController::class)->except('edit');
    Route::resource('certificates', CertificateController::class)->except('edit', 'show');
    Route::resource('comments', CommentController::class)->only('destroy');
    Route::resource('companies', CompanyController::class)->only('index');;
    Route::resource('licenses', LicenseController::class)->only('update', 'store', 'create');
    Route::resource('partners', PartnerController::class)->only('index');
    Route::resource('questionnaires', QuestionnaireController::class)->only('update', 'store', 'create');
    Route::resource('tests', TestController::class)->only('index', 'store');
    Route::resource('trainings', TrainingController::class)->only('index');
    Route::resource('universities', UniversityController::class)->except('index', 'show');
    Route::resource('users', UserController::class);
    Route::resource('works', WorkController::class)->except('index', 'show');
    Route::resource('types', \App\Http\Controllers\TypeController::class)->only('show');
    Route::resource('answers', \App\Http\Controllers\AnswerController::class)->only('index');
    Route::resource('meetings', \App\Http\Controllers\MeetingController::class)->only('index', 'create');
    Route::resource('books', \App\Http\Controllers\BookController::class)->only('index');
    Route::resource('suggestions', \App\Http\Controllers\SuggestionController::class)->only('index');
    Route::resource('likes', \App\Http\Controllers\LikeController::class)->only('store');
    Route::resource('votes', \App\Http\Controllers\VoteController::class)->only('store', 'destroy');
    Route::resource('subcomments', \App\Http\Controllers\SubcommentController::class)->only('destroy', 'store');
    Route::get('/trainings/{category}', [TrainingController::class, 'show'])->name('trainings.show');
    Route::post('/trainings/next', [TrainingController::class, 'showNext'])->name('trainings.next');
    Route::post('/trainings/previous', [TrainingController::class, 'showPrevious'])->name('trainings.previous');
    Route::get('/tests/category/{category}', [TestController::class, 'create'])->name('tests.create');
    Route::post('/callback/{user?}', [\App\Http\Controllers\CallbackController::class, 'store'])->name('callbacks.store');
    Route::delete('likes/destroy', [\App\Http\Controllers\LikeController::class, 'destroy'])->name('likes.destroy');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::post('users/{user}/comments', [CommentController::class, 'store'])->name('comments.store');
    Route::post('/zoom/store', [\App\Http\Controllers\ZoomController::class, 'store'])->name('zoom.store');
    Route::delete('/zoom/{meeting}', [\App\Http\Controllers\ZoomController::class, 'destroy'])->name('zoom.destroy');
    Route::get('/user/mediators', [UserController::class, 'mediators'])->name('users.mediators');
    Auth::routes(['verify' => true]);
});

Route::get('language/{locale}', [LanguageSwitcherController::class, 'switcher'])
    ->name('language.switcher')
    ->where('locale', 'en|ru');

Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware('auth')->name('verification.notice');
Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();
    return redirect('/home');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::get('/sms', function () {
    \Illuminate\Support\Facades\Notification::send(auth()->user(), new \App\Notifications\WelcomeNotification());
});
Route::get('/auth/facebook', [\App\Http\Controllers\SocialController::class, 'facebookRedirect'])->name('auth.facebook');
Route::get('/auth/facebook/callback', [\App\Http\Controllers\SocialController::class, 'loginWithFacebook'])->name('loginWithFacebook');

resources/views/licenses/create.blade.php
@extends('layouts.app')

@section('content')
    @include('navbar.navbar')
    <div class="container rounded bg-white mt-5 mb-5">
        <div class="row">
            <div class="col-md-3 border-right">
                <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                    @if(isset($user->questionnaire->picture))
                        <img class="rounded-circle mt-5" width="150px" height="150px"
                             src="{{asset('/storage/' . $user->questionnaire->picture)}}" alt="#">
                    @else
                        <img class="rounded-circle mt-5" width="150px" height="150px"
                             src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg"
                             alt="#">
                    @endif
                    <span class="font-weight-bold">{{Auth::user()->name}}</span>
                    <span class="text-black-50">{{Auth::user()->email}}</span>
                </div>
            </div>
            <div class="col-md-5 border-right">
                <div class="p-3 py-5">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h4 class="text-right">{{__('License')}}</h4>
                    </div>
                    <div class="row mt-3">
                        <form action="{{route('licenses.store')}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="col-md-12">
                                <label for="start_date" class="form-label @error('description') is-invalid @enderror"> {{__('Start date')}}</label>
                                <input name="start_date" type="date" class="form-control" id="start_date"
                                       placeholder="Start date">
                            </div>
                            <div class="col-md-12">
                                <label for="finish_date" class="form-label @error('description') is-invalid @enderror"> {{__('Finish date')}}</label>
                                <input name="finish_date" type="date" class="form-control" id="finish_date"
                                       placeholder="Finish date">
                            </div>
                            <div class="col-md-12">
                                <label for="description" class="form-label">{{__('Description')}}</label>
                                <textarea class="form-control @error('description') is-invalid @enderror"
                                          id="description" rows="3" name="description">{{  old('description') }}</textarea>
                                @error('description')
                                <span class="invalid-feedback"
                                      role="alert"><strong>{{ $message }}</strong></span>
                                @enderror
                            </div>

                            <div class="col-md-12">
                                <label for="number" class="form-label">{{__('Number')}}</label>
                                <input class="form-control @error('number') is-invalid @enderror" type="text"
                                       id="number" name="number" value="{{ old('number') }}"/>
                                @error('number')
                                <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                                @enderror
                            </div>
                            <div class="col mt-3 ml-3" style="width: 375px; text-align: center;">
                                <input type="file" class="custom-file-input" id="picture" name="picture">
                                <label class="custom-file-label" for="picture">{{__('Choose file')}}</label>
                            </div>
                            <button type="submit" class="boxed-btn5 mt-5 w-100">{{__('Create')}}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/licenses/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('navbar.navbar')
    <div class="container rounded bg-white mt-5 mb-5">
        <div class="row">
            <div class="col-md-3 border-right">
                <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                    @if(isset($user->questionnaire->picture))
                        <img class="rounded-circle mt-5" width="150px" height="150px"
                             src="{{asset('/storage/' . $user->questionnaire->picture)}}"
                             alt="{{$user->questionnaire->picture}}">
                    @else
                        <img class="rounded-circle mt-5" width="150px" height="150px"
                             alt="#"
                             src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg">
                    @endif
                    <span class="font-weight-bold">{{$user->name}}</span><span
                        class="text-black-50">{{$user->email}}</span>
                </div>
            </div>
            <div class="col-md-5 border-right">
                <div class="p-3 py-5">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h4 class="text-right">{{__('Update')}} {{__('License')}}</h4>
                    </div>
                    <div class="row mt-3">
                        <form action="{{route('licenses.update', ['license' => $license])}}" method="POST"
                              enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="col-md-12">
                                <label for="start_date" class="form-label @error('description') is-invalid @enderror"> {{__('Start date')}}</label>
                                <input name="start_date" type="date" class="form-control" id="start_date"
                                       value="{{$license->start_date}}">
                                @error('start_date')
                                <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                                @enderror
                            </div>
                            <div class="col-md-12">
                                <label for="finish_date" class="form-label @error('description') is-invalid @enderror"> {{__('Finish date')}}</label>
                                <input name="finish_date" type="date" class="form-control" id="finish_date"
                                       value="{{$license->finish_date}}">
                                @error('finish_date')
                                <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                                @enderror
                            </div>
                            <div class="col-md-12">
                                <label for="description" class="form-label">{{__('Description')}}</label>
                                <textarea class="form-control @error('description') is-invalid @enderror"
                                          id="description" rows="4"
                                          name="description">{{$license->description}}</textarea>
                                @error('description')
                                <span class="invalid-feedback"
                                      role="alert"><strong>{{ $message }}</strong></span>
                                @enderror
                            </div>
                            <div class="col-md-12">
                                <label for="number" class="form-label">{{__('Number')}}</label>
                                <input class="form-control @error('number') is-invalid @enderror" type="text" id="number" name="number" value="{{$license->number}}"/>
                                @error('number')
                                <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                                @enderror
                            </div>
                            <div class="col mt-3 ml-3" style="width: 375px; text-align: center;">
                                <input type="file" class="custom-file-input" id="picture" name="picture">
                                <label class="custom-file-label" for="picture">{{__('Choose file')}}</label>
                            </div>
                            <button type="submit" class="boxed-btn5 mt-5 w-100">{{__('Update')}}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection