routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CertificateController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\LanguageSwitcherController;
use App\Http\Controllers\LicenseController;
use App\Http\Controllers\PartnerController;
use App\Http\Controllers\QuestionnaireController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\TrainingController;
use App\Http\Controllers\UniversityController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WorkController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware(['language'])->group(function () {
    Route::get('/', [CompanyController::class, 'index']);
    Route::resource('categories', CategoryController::class)->except('edit');
    Route::resource('certificates', CertificateController::class)->except('edit', 'show');
    Route::resource('comments', CommentController::class)->only('destroy');
    Route::resource('companies', CompanyController::class)->only('index');;
    Route::resource('licenses', LicenseController::class)->only('update', 'store', 'create');
    Route::resource('partners', PartnerController::class)->only('index');
    Route::resource('questionnaires', QuestionnaireController::class)->only('update', 'store', 'create');
    Route::resource('tests', TestController::class)->only('index', 'store');
    Route::resource('trainings', TrainingController::class)->only('index');
    Route::resource('universities', UniversityController::class)->except('index', 'show');
    Route::resource('users', UserController::class);
    Route::resource('works', WorkController::class)->except('index', 'show');
    Route::resource('types', \App\Http\Controllers\TypeController::class)->only('show');
    Route::resource('answers', \App\Http\Controllers\AnswerController::class)->only('index');
    Route::resource('meetings', \App\Http\Controllers\MeetingController::class)->only('index', 'create');
    Route::resource('books', \App\Http\Controllers\BookController::class)->only('index');
    Route::resource('suggestions', \App\Http\Controllers\SuggestionController::class)->only('index');
    Route::resource('likes', \App\Http\Controllers\LikeController::class)->only('store');
    Route::resource('votes', \App\Http\Controllers\VoteController::class)->only('store', 'destroy');
    Route::resource('subcomments', \App\Http\Controllers\SubcommentController::class)->only('destroy', 'store');
    Route::get('/trainings/{category}', [TrainingController::class, 'show'])->name('trainings.show');
    Route::post('/trainings/next', [TrainingController::class, 'showNext'])->name('trainings.next');
    Route::post('/trainings/previous', [TrainingController::class, 'showPrevious'])->name('trainings.previous');
    Route::get('/tests/category/{category}', [TestController::class, 'create'])->name('tests.create');
    Route::post('/callback/{user?}', [\App\Http\Controllers\CallbackController::class, 'store'])->name('callbacks.store');
    Route::delete('likes/destroy', [\App\Http\Controllers\LikeController::class, 'destroy'])->name('likes.destroy');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::post('users/{user}/comments', [CommentController::class, 'store'])->name('comments.store');
    Route::post('/zoom/store', [\App\Http\Controllers\ZoomController::class, 'store'])->name('zoom.store');
    Route::delete('/zoom/{meeting}', [\App\Http\Controllers\ZoomController::class, 'destroy'])->name('zoom.destroy');
    Route::get('/user/mediators', [UserController::class, 'mediators'])->name('users.mediators');
    Auth::routes(['verify' => true]);
});

Route::get('language/{locale}', [LanguageSwitcherController::class, 'switcher'])
    ->name('language.switcher')
    ->where('locale', 'en|ru');

Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware('auth')->name('verification.notice');
Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();
    return redirect('/home');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::get('/sms', function () {
    \Illuminate\Support\Facades\Notification::send(auth()->user(), new \App\Notifications\WelcomeNotification());
});
Route::get('/auth/facebook', [\App\Http\Controllers\SocialController::class, 'facebookRedirect'])->name('auth.facebook');
Route::get('/auth/facebook/callback', [\App\Http\Controllers\SocialController::class, 'loginWithFacebook'])->name('loginWithFacebook');

app/Models/Suggestion.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * @method static orderBy(string $string)
 * @method static findOrFail(mixed $get)
 */
class Suggestion extends Model
{
    use HasFactory;

    protected $fillable = ['suggestion', 'start_date', 'finish_date'];

    public function votes(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Vote::class);
    }
}

app/Http/Controllers/Api/SuggestionController.php
<?php
namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\VoteRequest;
use App\Http\Resources\SuggestionResource;
use App\Models\Suggestion;
use App\Models\User;
use App\Models\Vote;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\Routing\ResponseFactory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;

class SuggestionController extends Controller
{
    /**
     * @return AnonymousResourceCollection
     * @throws AuthorizationException
     */
    public function index(): AnonymousResourceCollection
    {
        $this->authorize('viewAny', User::class);
        $suggestion = Suggestion::all();
        return SuggestionResource::collection($suggestion);
    }

    /**
     * @param VoteRequest $request
     * @return Application|ResponseFactory|Response
     */
    public function store(VoteRequest $request)
    {
        $vote = new Vote($request->all());
        $vote->user_id = Auth::id();
        $vote->save();
        return response(['id' => $vote->suggestion_id],201);
    }

    /**
     * @param Suggestion $suggestion
     * @return Application|ResponseFactory|Response
     * @throws AuthorizationException
     */
    public function destroy(Suggestion $suggestion)
    {
        $this->authorize('viewAny', User::class);
        $vote = Auth::user()->votes->where('suggestion_id', $suggestion->id)->first();
        $vote->delete();
        return response([],204);
    }

    /**
     * @return JsonResponse
     */
    public function getUser(): JsonResponse
    {
        $votes = Auth::user()->votes;
        $new_votes = [];
        foreach ($votes as $vote) {
            $new_votes[] = $vote->suggestion_id;
        }
        return response()->json([
            'votes' => $new_votes,
        ]);
    }
}

app/Http/Controllers/SuggestionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Suggestion;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;

class SuggestionController extends Controller
{
    public function __construct()
    {
        return $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $suggestions = Suggestion::all();
        return view('suggestions.index', compact('suggestions'));
    }
}

resources/views/suggestions/index.blade.php
@extends('layouts.app')

@section('content')

    @foreach($suggestions as $suggestion)
        <div class="card mt-3">
            <div class="card-header">
                {{__('Valid')}} {{__('from')}} {{$suggestion->start_date}} {{__('until')}} {{$suggestion->finish_date}}
            </div>
            <div class="card-body">
                <h5 class="card-title">{{__('Suggestion')}} # {{$loop->iteration}}</h5>
                <p class="card-text">{{$suggestion->suggestion}}</p>
                <p class="card-text">{{__('For')}} {{$suggestion->votes->where('agree', true)->count()}}</p>
                <p class="card-text">{{__('Against')}} {{$suggestion->votes->where('agree', false)->count()}}</p>
                @if(\Illuminate\Support\Facades\Auth::user()->votes->where('suggestion_id', $suggestion->id)->first())
                    <form method="POST" action="{{route('votes.destroy', ['vote' => \Illuminate\Support\Facades\Auth::user()->votes->where('suggestion_id', $suggestion->id)->first()])}}">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-outline-primary">{{__('Change my mind')}}</button>
                    </form>
                @else
                    <div class="d-flex">
                        <form method="POST" action="{{route('votes.store')}}">
                            @csrf
                            <input type="hidden" value="{{$suggestion->id}}" name="suggestion_id">
                            <input type="hidden" name="agree" value="1">
                            <button class="btn btn-outline-success" type="submit">{{__('Agree')}}</button>
                        </form>
                        <form class="mx-2" method="POST" action="{{route('votes.store')}}">
                            @csrf
                            <input type="hidden" value="{{$suggestion->id}}" name="suggestion_id">
                            <button class="btn btn-outline-danger" type="submit">{{__('Disagree')}}</button>
                        </form>
                    </div>
                @endif
            </div>
        </div>
    @endforeach

@endsection