routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CertificateController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\LanguageSwitcherController;
use App\Http\Controllers\LicenseController;
use App\Http\Controllers\PartnerController;
use App\Http\Controllers\QuestionnaireController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\TrainingController;
use App\Http\Controllers\UniversityController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WorkController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware(['language'])->group(function () {
    Route::get('/', [CompanyController::class, 'index']);
    Route::resource('categories', CategoryController::class)->except('edit');
    Route::resource('certificates', CertificateController::class)->except('edit', 'show');
    Route::resource('comments', CommentController::class)->only('destroy');
    Route::resource('companies', CompanyController::class)->only('index');;
    Route::resource('licenses', LicenseController::class)->only('update', 'store', 'create');
    Route::resource('partners', PartnerController::class)->only('index');
    Route::resource('questionnaires', QuestionnaireController::class)->only('update', 'store', 'create');
    Route::resource('tests', TestController::class)->only('index', 'store');
    Route::resource('trainings', TrainingController::class)->only('index');
    Route::resource('universities', UniversityController::class)->except('index', 'show');
    Route::resource('users', UserController::class);
    Route::resource('works', WorkController::class)->except('index', 'show');
    Route::resource('types', \App\Http\Controllers\TypeController::class)->only('show');
    Route::resource('answers', \App\Http\Controllers\AnswerController::class)->only('index');
    Route::resource('meetings', \App\Http\Controllers\MeetingController::class)->only('index', 'create');
    Route::resource('books', \App\Http\Controllers\BookController::class)->only('index');
    Route::resource('suggestions', \App\Http\Controllers\SuggestionController::class)->only('index');
    Route::resource('likes', \App\Http\Controllers\LikeController::class)->only('store');
    Route::resource('votes', \App\Http\Controllers\VoteController::class)->only('store', 'destroy');
    Route::resource('subcomments', \App\Http\Controllers\SubcommentController::class)->only('destroy', 'store');
    Route::get('/trainings/{category}', [TrainingController::class, 'show'])->name('trainings.show');
    Route::post('/trainings/next', [TrainingController::class, 'showNext'])->name('trainings.next');
    Route::post('/trainings/previous', [TrainingController::class, 'showPrevious'])->name('trainings.previous');
    Route::get('/tests/category/{category}', [TestController::class, 'create'])->name('tests.create');
    Route::post('/callback/{user?}', [\App\Http\Controllers\CallbackController::class, 'store'])->name('callbacks.store');
    Route::delete('likes/destroy', [\App\Http\Controllers\LikeController::class, 'destroy'])->name('likes.destroy');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::post('users/{user}/comments', [CommentController::class, 'store'])->name('comments.store');
    Route::post('/zoom/store', [\App\Http\Controllers\ZoomController::class, 'store'])->name('zoom.store');
    Route::delete('/zoom/{meeting}', [\App\Http\Controllers\ZoomController::class, 'destroy'])->name('zoom.destroy');
    Route::get('/user/mediators', [UserController::class, 'mediators'])->name('users.mediators');
    Auth::routes(['verify' => true]);
});

Route::get('language/{locale}', [LanguageSwitcherController::class, 'switcher'])
    ->name('language.switcher')
    ->where('locale', 'en|ru');

Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware('auth')->name('verification.notice');
Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();
    return redirect('/home');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::get('/sms', function () {
    \Illuminate\Support\Facades\Notification::send(auth()->user(), new \App\Notifications\WelcomeNotification());
});
Route::get('/auth/facebook', [\App\Http\Controllers\SocialController::class, 'facebookRedirect'])->name('auth.facebook');
Route::get('/auth/facebook/callback', [\App\Http\Controllers\SocialController::class, 'loginWithFacebook'])->name('loginWithFacebook');

app/Models/Partner.php
<?php

namespace App\Models;

use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Orchid\Filters\Filterable;
use Orchid\Screen\AsSource;

class Partner extends Model implements TranslatableContract
{
    use HasFactory;
    use Translatable;
    use AsSource;
    use Filterable;


    /**
     * @var array|string[]
     */
    public array $translatedAttributes = ['name', 'description'];
    /**
     * @var string[]
     */
    protected $fillable = ['picture'];
}

app/Http/Controllers/Api/PartnerController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\PartnerResource;
use App\Models\Partner;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

class PartnerController extends Controller
{
    /**
     * @return AnonymousResourceCollection
     */
    public function index():AnonymousResourceCollection
    {
        $partners = Partner::all();
        return PartnerResource::collection($partners);
    }

    /**
     * @param Partner $partner
     * @return PartnerResource
     */
    public function show(Partner $partner):PartnerResource
    {
        return new PartnerResource($partner);
    }
}

app/Http/Controllers/PartnerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Partner;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;

class PartnerController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $partners = Partner::all();
        return view('partners.index', compact('partners'));
    }
}

resources/views/partners/card-partner.blade.php
<div class="col">
    <div class="card" style="width: 18rem;">
        <img src="{{asset('storage/' . $partner->picture)}}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title"><a href="{{route('partners.show', ['partner' => $partner])}}">{{$partner->name}}</a></h5>
            <p class="card-text">{{$partner->description}}</p>
        </div>
    </div>
</div>

resources/views/partners/index.blade.php
@extends('layouts.app')
@section('content')

    @include('callbacks.callback')

    <h1>{{__('Partners')}}</h1>
    <div class="row">
        <div class="about_area">
            <div class="opacity_icon d-none d-lg-block">
                <i class="flaticon-balance"></i>
            </div>
            <div class="container">
                <div class="row">
                    @foreach($partners as $partner)
                        <div class="col-xl-6 col-md-6">
                            <div class="single_about_info text-center">
                                <div class="about_thumb">
                                    <img src="{{asset('/storage/' . $partner->picture)}}" alt="">
                                </div>
                                <h3>{{$partner->name}}<br>
                                </h3>
                                <p>{{$partner->description}}</p>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/partners/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="card" style="width: 18rem;">
        <img src="{{asset('storage/' . $partner->picture)}}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title"><a href="{{route('partners.show', ['partner' => $partner])}}">{{$partner->name}}</a></h5>
            <p class="card-text">{{$partner->description}}</p>
        </div>
    </div>
@endsection